name: Generate Chinese calendar 
env:
  TZ: Asia/Shanghai
on:
  workflow_dispatch:
  schedule:
    - cron: "00 03 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install requirment  
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          apt-get update
          apt-get -y install python3-pip
          pip install -r requirements.txt
        shell: bash
